// ABOUTME: Page explaining the Human-Created certification badge
// ABOUTME: Describes criteria for displaying the badge and links to no-ai-icon.com

import { Brain, Shield, Video, ExternalLink } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

export default function HumanCreatedPage() {
  return (
    <div className="container max-w-4xl mx-auto px-4 py-8">
      <div className="space-y-8">
        {/* Header */}
        <div className="text-center space-y-4">
          <div className="flex items-center justify-center gap-3">
            <Brain className="h-12 w-12 text-purple-600" />
            <h1 className="text-4xl font-bold">Human-Created Content</h1>
          </div>
          <p className="text-xl text-muted-foreground">
            Certifying authentic, human-made videos on Divine Web
          </p>
        </div>

        {/* What is the Badge */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Brain className="h-5 w-5 text-purple-600" />
              What is the Human-Made Badge?
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              The <span className="font-semibold text-purple-600">Human-Made</span> badge certifies that a video
              was created by a real person, not generated by artificial intelligence. This badge helps you identify
              authentic content in an era where AI-generated videos are becoming increasingly common.
            </p>
            <p>
              We believe people should always be able to know if the content they consume is made by humans or
              artificial intelligence. This initiative is inspired by{' '}
              <a
                href="https://no-ai-icon.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary hover:underline inline-flex items-center gap-1"
              >
                no-ai-icon.com
                <ExternalLink className="h-3 w-3" />
              </a>
              , which provides free badges for creators to certify their work.
            </p>
          </CardContent>
        </Card>

        {/* When the Badge Appears */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Video className="h-5 w-5 text-purple-600" />
              When Does This Badge Appear?
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-4">
              <div>
                <h3 className="font-semibold mb-2">1. Original Vine Videos (Automatic)</h3>
                <p className="text-muted-foreground">
                  All videos migrated from the original Vine platform (2013-2017) automatically display this badge.
                  These videos were created before modern AI video generation existed, making them verifiably
                  human-created.
                </p>
              </div>

              <div>
                <h3 className="font-semibold mb-2">2. Creator-Claimed Content</h3>
                <p className="text-muted-foreground">
                  Content creators can add a <code className="text-sm bg-muted px-1 py-0.5 rounded">human-created</code>{' '}
                  tag to their video events to claim their work is 100% human-made. We trust creators to be honest
                  about their content's origins.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* ProofMode Integration */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="h-5 w-5 text-purple-600" />
              How This Relates to ProofMode
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              The Human-Made badge complements our{' '}
              <span className="font-semibold text-green-600">ProofMode</span> verification system:
            </p>
            <ul className="space-y-2 list-disc list-inside text-muted-foreground">
              <li>
                <span className="font-semibold text-foreground">ProofMode</span> provides cryptographic proof that
                media is authentic and unmodified, with hardware-level attestation from mobile devices
              </li>
              <li>
                <span className="font-semibold text-foreground">Human-Made</span> certifies the content was created
                by humans, not AI-generated
              </li>
            </ul>
            <p>
              Together, these badges help build a more transparent and trustworthy platform where you can be confident
              about what you're watching.
            </p>
          </CardContent>
        </Card>

        {/* For Content Creators */}
        <Card>
          <CardHeader>
            <CardTitle>For Content Creators</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              If you're creating videos for Divine Web and want to claim your work as human-created, add a{' '}
              <code className="text-sm bg-muted px-1 py-0.5 rounded">human-created</code> tag to your video events.
              This helps your audience know they're watching authentic, human-made content.
            </p>
            <div className="bg-muted p-4 rounded-lg">
              <p className="text-sm font-mono">
                tags: [["t", "human-created"]]
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Learn More */}
        <div className="flex justify-center">
          <Button asChild variant="outline" size="lg">
            <a
              href="https://no-ai-icon.com"
              target="_blank"
              rel="noopener noreferrer"
              className="gap-2"
            >
              Learn More at no-ai-icon.com
              <ExternalLink className="h-4 w-4" />
            </a>
          </Button>
        </div>
      </div>
    </div>
  );
}
